[package]
name = "mocknet"
version = "0.1.0"
edition = "2018"

[[bin]] # Bin to run the HelloWorld gRPC server
name = "mocknet-master"
path = "src/master.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "mocknet-slave"
path = "src/slave.rs"

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.2"