[package]
name = "mocknet"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[[bin]] 
name = "container_server"
path = "src/bins/container_server.rs"

[[bin]]
name = "mocknet_backend"
path = "src/bins/mocknet_backend.rs"

[[bin]]
name = "test_indradb"
path = "src/bins/test_indradb.rs"

[dependencies]
tonic = "0.2"
prost = "0.6"
tokio = { version = "0.2", features = ["macros", "process"] }
tower = { version = "0.3" }
dummy_cli_parser = { git = "https://github.com/duanjp8617/dummy_cli_parser.git", branch = "master" }
capnp = "0.13.3"
capnp-rpc = "0.13.1"
indradb-lib = "1.1.0"


[build-dependencies]
tonic-build = "0.2"
capnpc = "0.13.1"